### ISSUE TITLE
Hide some type of train stations

### ISSUE THREAD

**Issue by FKuerten** [folknor/factorio-shuttle#2]
I am using Logistic Train Network which uses its own train station entity ["train-stop"]["logistic-train-stop"].
Could we get an option to hide filter based upon the train station type?
Maybe a check box "show non-default train-stops"?
Or an option to explicitly exclude that one?

**Comment by folknor** [comment]
Yes, this is possible to a certain extent.
The mod settings parsing happens before the data parsing for mods (http://lua-api.factorio.com/latest/Data-Lifecycle.html), which means that when I construct the settings, I don't really know the identifiers used by 3rd party mods to add in their alternative train stops - or even whether or not they will add in any 3rd party train stops at all.

What I do have access to when constructing settings is which mods are present and enabled, by name/version.

So I can't add options per train station type dynamically. I would have to add explicit support on a per-mod basis.

Which means I can add an option that says, for example, "Show Logistic Train Network stops", and only show that option if LTN is present. But then I have to hardcode the reference to ["train-stop"]["logistic-train-stop"] later, and if that ID changes, or is removed, the option won't automatically reflect this or work. I don't consider this a problem - the ID is unlikely to change or be removed.

I can also add a generic "Show non-default train stops", but I prefer a LTN-specific one, so that if someone else uses a different mod that adds train stops, they can easily see that they can ask me to support it.
The bonus with a "non-default" option is that I could make it dynamic in the sense that it would catch all 3rd party train stops.

So, the question is how should the setting behave? Should it
1. Show/hide the stations permanently from the GUI
1. Show/hide the stations when the GUI is _not_ filtered
1. Show/hide the stations when the GUI _is_ filtered
